services:
  database:
    image: mariadb:11.8
    ports:
      - "3306:3306"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=true"
      - "MARIADB_DATABASE=testvault"
      - "MARIADB_USER=<USER>"
      - "MARIADB_PASSWORD=<PASS>"
  vault:
    image: openbao/openbao:2.2
    ports:
      - "8200:8200"