app:
  base-user:
    username: ${TESTVAULT_USERNAME:root}
    password: ${TESTVAULT_PASSWORD:#{null}}

spring:
  application.name: testvault

  cloud.vault:
    uri: http://localhost:8200
    token: <TOKEN>

  config.import: vault://

  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/testvault
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update

springdoc.show-login-endpoint: true